version: '3.8'

services:
  mmm:
    build:
      context: .
    volumes:
        - ./:/home/MMMwebpage
    links:
      - mysqldb
    depends_on:
      - mysqldb
    env_file:
      - '.env'
    ports:
      - '5000:5000'

  mysqldb:
    image: mysql/mysql-server:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_USER: max
      MYSQL_PASSWORD: 8883868
      MYSQL_DATABASE: MMM
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

